modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="sporebound"
version="${version}"
displayName="Sporebound: The Blighted World"
authors="OuterRingFoundry"
description='''A quarantined fungal dimension, persistent corruption progression, and protected mushroom islands. An independent Fungal Infection: Spore addon.'''
[[mixins]]
config="sporebound.mixins.json"
[[dependencies.sporebound]]
modId="neoforge"
type="required"
versionRange="[21.1.249,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.sporebound]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[dependencies.sporebound]]
modId="spore"
type="required"
versionRange="[2.2.0j]"
ordering="AFTER"
side="BOTH"
